# -*- coding: utf-8 -*-
"""อะไรสักอย่าง เอาไว้ตอนจะทำDockerค่อยใช้อ้างอิงค์.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDMrb3iuqCayV0be8bG9k-vPcFEhtXlm
"""

2. ไฟล์เพิ่มเติมสำหรับ MCP Core

"""mcp_core/compliance_checker.py

"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compliance Checker Module"""

class ComplianceChecker:
    """ตรวจสอบมาตรฐาน"""

    @staticmethod
    def check_mea_compliance(wire_size: float, current: float,
                           room_type: str) -> List[Dict[str, Any]]:
        """ตรวจสอบตามมาตรฐาน MEA"""
        violations = []

        # Minimum wire size for kitchen
        if room_type == "kitchen" and wire_size < 2.5:
            violations.append({
                "code": "MEA_MIN_WIRE_KITCHEN",
                "severity": "ERROR",
                "message": "ห้องครัวต้องใช้สายขนาดอย่างน้อย 2.5 มม."
            })

        # Maximum outlets per circuit
        if current > 16:
            violations.append({
                "code": "MEA_MAX_OUTLETS",
                "severity": "WARNING",
                "message": "กระแสเกิน 16A ควรแยกวงจร"
            })

        return violations

"""mcp_core/layout_optimizer.py"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Layout Optimizer Module"""

import math

class LayoutOptimizer:
    """คำนวณระยะทางที่สั้นที่สุด"""

    @staticmethod
    def optimize_outlet_placement(room_width: float, room_length: float,
                                spacing: float = 1200) -> List[Dict[str, float]]:
        """หาตำแหน่งที่เหมาะสมสำหรับติดตั้ง outlet"""

        placements = []

        # Along walls
        # Top wall
        x = spacing
        while x < room_width - spacing:
            placements.append({"x": x, "y": 100})
            x += spacing

        # Bottom wall
        x = spacing
        while x < room_width - spacing:
            placements.append({"x": x, "y": room_length - 100})
            x += spacing

        # Left wall
        y = spacing
        while y < room_length - spacing:
            placements.append({"x": 100, "y": y})
            y += spacing

        # Right wall
        y = spacing
        while y < room_length - spacing:
            placements.append({"x": room_width - 100, "y": y})
            y += spacing

        return placements

"""mcp_core/conduit_sizer.py"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Conduit Sizer Module"""

class ConduitSizer:
    """เลือกขนาดท่อ"""

    # Conduit sizes and fill capacity
    CONDUIT_SIZES = {
        16: {"area": 201, "max_fill": 0.4},  # mm²
        20: {"area": 314, "max_fill": 0.4},
        25: {"area": 491, "max_fill": 0.4},
        32: {"area": 804, "max_fill": 0.4}
    }

    # Wire areas
    WIRE_AREAS = {
        1.5: 7.1,
        2.5: 11.9,
        4.0: 19.0,
        6.0: 28.8
    }

    @classmethod
    def select_conduit_size(cls, wire_sizes: List[float],
                           wire_count: List[int]) -> Dict[str, Any]:
        """เลือกขนาดท่อตามจำนวนและขนาดสาย"""

        total_wire_area = 0
        for size, count in zip(wire_sizes, wire_count):
            wire_area = cls.WIRE_AREAS.get(size, 0)
            total_wire_area += wire_area * count

        # Select conduit size
        for size, data in sorted(cls.CONDUIT_SIZES.items()):
            max_fill_area = data["area"] * data["max_fill"]
            if total_wire_area <= max_fill_area:
                return {
                    "size_mm": size,
                    "area_mm2": data["area"],
                    "fill_pct": (total_wire_area / data["area"]) * 100,
                    "wire_area_total": total_wire_area
                }

        # Return largest if none fits
        largest = max(cls.CONDUIT_SIZES.keys())
        largest_data = cls.CONDUIT_SIZES[largest]

        return {
            "size_mm": largest,
            "area_mm2": largest_data["area"],
            "fill_pct": (total_wire_area / largest_data["area"]) * 100,
            "wire_area_total": total_wire_area,
            "warning": "Conduit may be overfilled"
        }

"""ไฟล์Requirement

"""

fastapi==0.104.1
uvicorn==0.24.0
pydantic==2.5.0
httpx==0.25.2
redis==5.0.1
python-multipart==0.0.6

"""4. ไฟล์ Dockerfile (สำหรับการ Deploy)"""

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /tmp/exports

EXPOSE 8080

CMD ["python", "amadeus_omega_server.py"]

"""การติดตั้งและรัน
สร้างโครงสร้างโฟลเดอร์:



"""

