# -*- coding: utf-8 -*-
"""Gate way new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNM85oWdLVsL8ZiGf-C7VUS-c1z17mVx
"""

# ═══════════════════════════════════════════════════════════════════
# ENHANCED INTENT CLASSIFICATION - LLM-Based Router
# ═══════════════════════════════════════════════════════════════════

import httpx
from typing import Optional

LLM_ROUTER_ENDPOINT = os.getenv("LLM_ROUTER_ENDPOINT", "http://localhost:11434/api/generate")
LLM_ROUTER_MODEL = os.getenv("LLM_ROUTER_MODEL", "qwen2.5:0.5b")

DIALOGUE_MANAGER_ENDPOINT = os.getenv("DIALOGUE_MANAGER_ENDPOINT", "http://localhost:8082")


class LLMRouter:
    """
    LLM-based intent router

    WHY: Regex cannot understand context or nuance.
    LLM can detect technical intent even in casual language.

    Example:
    - "เห้ย ช่วยออกแบบไฟห้องครัวหน่อย" → MOZART (technical)
    - "คุณคิดยังไงกับจริยธรรม AI" → AMADEUS (philosophical)
    """

    ROUTER_PROMPT = """You are an intent classifier for an engineering AI system.

The system has TWO modes:
1. MOZART (RAG/Engineering): Technical questions about electrical design, calculations, standards, AutoCAD
2. AMADEUS (AGI/Chat): General conversation, philosophy, ethics, non-technical questions

Examples:
User: "ออกแบบไฟห้องครัวให้หน่อย" → MOZART
User: "คำนวณ voltage drop ให้ที" → MOZART
User: "คุณคิดยังไงกับความหมายของชีวิต" → AMADEUS
User: "เล่าเรื่องตลกหน่อย" → AMADEUS

User input: "{user_input}"

Respond ONLY with: MOZART or AMADEUS
"""

    def __init__(self):
        self.client = httpx.AsyncClient(timeout=10.0)

    async def route_with_llm(
        self,
        user_input: str,
        dialogue_history: Optional[List[Dict]] = None
    ) -> RoutingDecision:
        """
        Route using LLM instead of regex

        WHY THIS IS BETTER:
        - Understands context from dialogue history
        - Can handle misspellings, slang, mixed languages
        - Higher accuracy than keyword matching
        """
        # Build prompt with context
        prompt = self.ROUTER_PROMPT.format(user_input=user_input)

        # Add dialogue history if available
        if dialogue_history:
            context = "\n".join([
                f"{msg['role']}: {msg['content']}"
                for msg in dialogue_history[-3:]  # Last 3 turns
            ])
            prompt = f"Previous context:\n{context}\n\n{prompt}"

        # Call LLM (Ollama API)
        try:
            response = await self.client.post(
                LLM_ROUTER_ENDPOINT,
                json={
                    "model": LLM_ROUTER_MODEL,
                    "prompt": prompt,
                    "stream": False
                }
            )
            response.raise_for_status()

            result = response.json()
            answer = result.get("response", "").strip().upper()

            if "MOZART" in answer:
                return RoutingDecision(
                    mode=IntentMode.COPILOT,
                    confidence=0.90,
                    reasoning="LLM detected technical/engineering intent",
                    keywords=["llm_classified"]
                )
            else:
                return RoutingDecision(
                    mode=IntentMode.AGI,
                    confidence=0.90,
                    reasoning="LLM detected conversational intent",
                    keywords=["llm_classified"]
                )

        except Exception as e:
            print(f"[GATEWAY] LLM router failed: {e}, falling back to regex")
            # Fallback to old regex method
            return self._fallback_regex_route(user_input)

    def _fallback_regex_route(self, user_input: str) -> RoutingDecision:
        """Fallback to regex if LLM fails"""
        # Original regex logic here
        ...


# Update orchestrate endpoint
@app.post("/orchestrate", response_model=GatewayResponse)
@trace_gateway(name="gateway_orchestrate")
async def orchestrate(
    request: GatewayRequest,
    x_trace_id: Optional[str] = Header(None)
) -> GatewayResponse:
    """
    Enhanced orchestrator with dialogue support

    New Flow:
    1. Check if this is part of ongoing dialogue
    2. If yes, route to Dialogue Manager first
    3. If dialogue complete, route to Mozart → MCP
    4. If not dialogue, use LLM router
    """
    start_time = time.time()
    trace_id = x_trace_id or f"gateway-{int(time.time() * 1000)}"

    # Check for ongoing dialogue session
    if request.session_id:
        # Forward to Dialogue Manager
        dialogue_response = await _handle_dialogue_turn(request, trace_id)

        if dialogue_response["ready_for_mcp"]:
            # Dialogue complete → Execute MCP
            mcp_result = await proxy.call_copilot(request, trace_id)

            return GatewayResponse(
                mode=IntentMode.COPILOT,
                data={
                    "dialogue": dialogue_response,
                    "mcp_result": mcp_result
                },
                processing_time_ms=int((time.time() - start_time) * 1000),
                trace_id=trace_id,
                routing_decision=RoutingDecision(
                    mode=IntentMode.COPILOT,
                    confidence=1.0,
                    reasoning="Dialogue completed, MCP executed",
                    keywords=["dialogue_complete"]
                )
            )
        else:
            # Continue dialogue
            return GatewayResponse(
                mode=IntentMode.COPILOT,
                data=dialogue_response,
                processing_time_ms=int((time.time() - start_time) * 1000),
                trace_id=trace_id,
                routing_decision=RoutingDecision(
                    mode=IntentMode.COPILOT,
                    confidence=1.0,
                    reasoning="Dialogue in progress",
                    keywords=["dialogue_turn"]
                )
            )

    # No dialogue → Use LLM router
    router = LLMRouter()
    decision = await router.route_with_llm(request.input)

    # Delegate to appropriate zone
    if decision.mode == IntentMode.COPILOT:
        data = await proxy.call_copilot(request, trace_id)
    else:
        data = await proxy.call_agi(request, trace_id)

    return GatewayResponse(
        mode=decision.mode,
        data=data,
        processing_time_ms=int((time.time() - start_time) * 1000),
        trace_id=trace_id,
        routing_decision=decision
    )


async def _handle_dialogue_turn(request: GatewayRequest, trace_id: str) -> Dict:
    """Helper to call Dialogue Manager"""
    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"{DIALOGUE_MANAGER_ENDPOINT}/dialogue/turn",
            json={
                "session_id": request.session_id,
                "user_id": request.user_id,
                "user_input": request.input
            },
            headers={"X-Trace-ID": trace_id}
        )
        response.raise_for_status()
        return response.json()